# Generated by Django 4.1.2 on 2022-12-04 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
