# Generated by Django 4.1.2 on 2022-12-06 21:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Question',
        ),
    ]
