# Generated by Django 4.1.2 on 2022-12-06 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('imdb', '0004_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=33)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=20)),
                ('role', models.IntegerField(choices=[(0, 'User'), (1, 'Admin')], default=0, max_length=1)),
            ],
        ),
    ]
