# Generated by Django 4.1.2 on 2022-12-06 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0006_alter_user_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserMoviesList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('Action', 'Action'), ('Adventure', 'Adventure'), ('Animated', 'Animated'), ('Comedy', 'Comedy'), ('Drama', 'Drama'), ('Fantasy', 'Fantasy'), ('Historical', 'Historical'), ('Horror', 'Horror'), ('Musical', 'Musical'), ('Romance', 'Romance'), ('Science Fiction', 'Science Fiction'), ('Thriller', 'Thriller'), ('Western', 'Western'), ('Other', 'Other')], default='Other', max_length=15)),
            ],
        ),
    ]
