# Generated by Django 4.1.2 on 2022-12-06 22:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0007_usermovieslist'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='lists',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='imdb.usermovieslist'),
        ),
    ]
