# Generated by Django 4.1.2 on 2022-12-06 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('imdb', '0008_user_lists'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='lists',
            new_name='film_lists',
        ),
        migrations.AddField(
            model_name='usermovieslist',
            name='is_public',
            field=models.BooleanField(default=True),
        ),
    ]
